### ISSUE TITLE
Problematic Briz-M RO/RF config

### ISSUE THREAD

**Issue by kiwivogel** [InsaneDruid/Proton-M#1]
Hello! I'm experiencing some trouble with your (otherwise fantastic) upper stage. The config is setup in such a way that both the upper stage vernier/RCS blocks and the main S5.98M engine require ullage. Last time I tried it was impossible to use the RCS function of the RCS blocks to ensure save engine ignition. I've had to resort to sticking some attitude jets on the bottom to get a functional upper stage. I'll try to do some research on the normal starting procedures for the real life equivalent. I'll fiddle around with the config for a bit to see if I can get a working config. Alternatively it might be good to set the tank type to something pressurized. Again, I'll try to find some literature on the actual configuration of the tanks.

**Comment by InsaneDruid** [comment]
Probably because the engines still use the old syntax. I'll look into this and update them.

**Comment by kiwivogel** [comment]
That'd be great.

**Comment by InsaneDruid** [comment]
I adjusted the code for the new syntax and removed the ullage requirement for the verniers on the vernier/RCS Thruster blocks. They now can provide ullage and fine control while the S5.98M can be restartet 8 times. (like austronautix states). Closing this issue, feel free and welcome to open another one if you see some problem zones.

**Comment by kiwivogel** [comment]
I still have issues, might have something to do with the fuel tank type but I have not been able to test that yet. Will try to fiddle with that some more this weekend. I'll also experiment with the RCS config itself. If I have a fix I'll send that as a pull request.

**Comment by InsaneDruid** [comment]
Ahh, I see. RO RCS config for briz still changes the Module to RCSFX! its only fixed in RF Stockalike. Fuel Tank change might still be a good idea though. I'll investigate.
