### ISSUE TITLE
New Proton Light configuration.

### ISSUE THREAD

**Issue by kiwivogel** [InsaneDruid/Proton-M#3]
According to a slide by ILS proton light features a stretched upper 3rd stage and a first stage that omits two fuel tanks and two engines and has an additional communal fuel tank shared by the four engines stacked on top of the oxidizer tank. I have no Idea if you want to put in the effort to change the base model to reflect these changes but it's an idea at least. [Picture here](https://pbs.twimg.com/media/CsNp3k2WIAAIeTC.jpg:large)

**Comment by InsaneDruid** [comment]
Interesting informations, thanks! Found the slide, too and some tweets about it from ILS. For now, I try to find infos about the actual length of the different extensions.
But first, the long overdue TKS/VA needs to be finished. But then, given the right dimensions I am quite keen to implement it. Would need an additional S1 texture though to remove the AO shades of the then missing two external tanks or some uv trickery/rework on the existing s1.

**Comment by kiwivogel** [comment]
TKS hype! <3

**Comment by InsaneDruid** [comment]
ILS has released the measurements of the medium and light new stages with mm accuracy! Sweet.

**Comment by kiwivogel** [comment]
I saw the pictures. Didn't get around to tell you but you found them yourself :D

**Comment by InsaneDruid** [comment]
New Medium & Light Configurations (as well as 5 meter Fairings for Proton M+) are added in the repository. No additional textures where needed.
